<a href="https://colab.research.google.com/github/jkrish006/DSA_assignments/blob/main/numpy_activites.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import numpy as np

In [20]:
# Create a NumPy array with values from 10 to 49 (inclusive).
# Reshape it into a 4x10 matrix.
# Then extract the last column from the reshaped matrix
array=np.arange(10,50)
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [21]:
matrix = array.reshape(4,10)
matrix

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [22]:
last_column= matrix[:,-1]
last_column

array([19, 29, 39, 49])

In [23]:
#  Create two 3×3 matrices:
# One filled with all 5s , One with values from 1 to 9
# Add the two matrices
# Multiply them element-wise
# Then find the transpose of the result
arr=np.full((3,3),5)
arr

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [24]:
arr2=np.arange(1,10)
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arr2=arr2.reshape(3,3)
matrix=arr+arr2
matrix



array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [26]:
transpose=matrix.T
transpose


array([[ 6,  9, 12],
       [ 7, 10, 13],
       [ 8, 11, 14]])

In [61]:
#  Create a NumPy array of 15 random integers between 10 and 100.
# ● Replace all values greater than 50 with -1
# ● Count how many values were replaced.
arr3=np.random.randint(10,101,15)
arr3


array([71, 32, 51, 80, 55, 39, 88, 65, 22, 25, 81, 33, 32, 85, 32])

In [62]:
count=np.sum(arr3>50)
count


np.int64(8)

In [65]:
replace=np.sum(arr3>50)
arr3[arr3>50]=-1
arr3

array([-1, 32, -1, -1, -1, 39, -1, -1, 22, 25, -1, 33, 32, -1, 32])

In [66]:
# Generate a 5×4 array with random values between 0 and 1 (float).
# ● Find the row with the maximum sum of values.
# ● Normalize each row using the formula:
matrix2=np.random.rand(5,4)
matrix2

array([[0.33786265, 0.76235191, 0.91526897, 0.11963026],
       [0.3675707 , 0.04072491, 0.82329263, 0.71438428],
       [0.03048126, 0.64897664, 0.81744967, 0.07259494],
       [0.59279018, 0.9928945 , 0.81540394, 0.84897947],
       [0.51590827, 0.25654409, 0.86405466, 0.43300841]])

In [74]:
row_sums = np.sum(matrix2, axis=1) #adding across rows
row_sums

array([2.13511379, 1.94597252, 1.5695025 , 3.2500681 , 2.06951543])

In [75]:
max_row=np.argmax(row_sums)
max_row

np.int64(3)

In [76]:
print(matrix2[max_row])

[0.59279018 0.9928945  0.81540394 0.84897947]


In [81]:
normalized = (matrix2 - matrix2.min(axis=1, keepdims=True)) / \
             (matrix2.max(axis=1, keepdims=True) - matrix2.min(axis=1, keepdims=True))
normalized

array([[0.27428578, 0.8078059 , 1.        , 0.        ],
       [0.41765816, 0.        , 1.        , 0.86083205],
       [0.        , 0.78592148, 1.        , 0.05351381],
       [0.        , 1.        , 0.5563893 , 0.64030624],
       [0.42692949, 0.        , 1.        , 0.29047119]])

In [86]:
# arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
# ● Find all unique elements
# ● Find the duplicates (elements that appear more than once)

arr01 = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
arr01

array([1, 3, 5, 3, 7, 9, 1, 5, 5])

In [94]:
np.unique(arr01)

array([1, 3, 5, 7, 9])

In [95]:
values,counts = np.unique(arr01, return_counts=True)
duplicates = values[counts > 1]
duplicates

array([1, 3, 5])

In [97]:
# Create a 6×6 NumPy array with values from 1 to 36.
# ● Extract the middle 4×4 submatrix.
# ● Then extract all even numbers from this submatrix.

arry=np.arange(1,37).reshape(6,6)
arry

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [101]:
sub=arry[1:5,1:5]
sub

array([[ 8,  9, 10, 11],
       [14, 15, 16, 17],
       [20, 21, 22, 23],
       [26, 27, 28, 29]])

In [103]:
even=sub[sub%2==0]
even

array([ 8, 10, 14, 16, 20, 22, 26, 28])

In [106]:
# Generate an array of shape (3, 4) with values from 0 to 11.
# ● Reshape it to (2, 6)
# ● Then flatten it into a 1D array
# ● Convert the 1D array back to shape (4, 3)

arry02=np.arange(12).reshape(3,4)
arry02

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [110]:
arry02=arry02.reshape(2,6)
arry02

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [112]:
flatten=arry02.flatten()
flatten

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [116]:
arry02=flatten.reshape(4,3)
arry02

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [135]:
#  Create an array: a = np.array([[1, 2], [3, 4]])
# ● Append a new row [5, 6]
# ● Then append a new column [7, 8, 9]

a = np.array([[1, 2], [3, 4]])
a


array([[1, 2],
       [3, 4]])

In [136]:
a_new=np.append(a,[[5,6]], axis=0)
a_new

array([[1, 2],
       [3, 4],
       [5, 6]])

In [131]:
col_a=np.array([7,8,9]).reshape(3,1)
col_a

array([[7],
       [8],
       [9]])

In [137]:
final=np.append(a_new,col_a,axis=1)
final

array([[1, 2, 7],
       [3, 4, 8],
       [5, 6, 9]])

In [139]:
# a = np.array([1, 2, 3])
# b = np.array([4, 5, 6])
# c = np.array([7, 8, 9])
# ● Join them into a single array
# ● Reshape the result into a 3×3 matrix
# ● Extract the diagonal elements

a_1 = np.array([1, 2, 3])
b_1 = np.array([4, 5, 6])
c_1 = np.array([7, 8, 9])

combined = np.concatenate((a_1, b_1, c_1))
combined

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [141]:
arr01=combined.reshape(3,3)
arr01

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [145]:
diagonal = np.diag(arr01)
diagonal

array([1, 5, 9])

In [146]:
# Create a NumPy array of integers from 1 to 20.
# ● Extract all values that are divisible by 3 or 5.
# ● Count how many such values exist.

arr_1 = np.arange(1, 21)
arr_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [149]:
extract = arr_1[(arr_1 % 3 == 0) | (arr_1 % 5 == 0)]
extract

array([ 3,  5,  6,  9, 10, 12, 15, 18, 20])

In [153]:
count=len(extract)
count

9